Update untether
w212security/wenetaunthreader pull request #3
Opened 2021-03-17 06:55 UTC by marijuanARM

2021-03-17 07:07 UTC, sqlstatement approved these changes
Looks good, I approximate ~99% better stability

2021-03-17 07:11 UTC, Ecstxsy approved these changes
Looks about right.

2021-03-17 07:14 UTC, DramaBinny approved these changes
approved by me

2021-03-17 07:20 UTC, asdfugil requested changes
this is shitcode

2021-03-17 07:20 UTC, Cryptiiiic approved these changes
joe

2021-03-17 10:34 UTC, syns reviewed
glad you added the sookhan exploit

2021-03-17 13:33 UTC, 23Aaron commented
If this request is accepted, I’d be glad to translate the repo into Sugondese

2021-03-17 14:33 UTC, 23Aaron approved these changes

2021-03-18 01:55 UTC, tale approved these changes
Great solution. Would recommend 100

2021-03-18 17:01 UTC, spacepilotAV commented
For the last goddamn time. This isn't Athenus and anyone who has watched any of the fucking demo videos would know that.

2021-03-18 17:01 UTC, closed without merging

2021-03-18 17:10 UTC, 0x14307 commented
for the last goddamn time, you fooling people with a "jailbreak" don't mean shit

2021-03-18 17:32 UTC, 0x14307 reviewed
its good just actually merge it

2021-03-18 17:38 UTC, spacepilotAV commented
We never claimed we had a jailbreak. Just code execution, which is factually correct. Stop putting words in our fucking mouths and acting like we said something we didn't.

2021-03-18 17:42 UTC, 0x14307 commented
![image](https://user-images.githubusercontent.com/56172613/111671875-98b9da00-87d6-11eb-8458-7e00b25b4c0b.png)

code execution = tfp0 = jelbrek

2021-03-18 17:43 UTC, 0x14307 commented
![image](https://user-images.githubusercontent.com/56172613/111672016-c0a93d80-87d6-11eb-8b4c-380e22dfefb2.png)

2021-03-18 17:53 UTC, spacepilotAV commented
Where does that claim a jailbreak?

2021-03-18 17:53 UTC, spacepilotAV commented
Also, take a look at this!
https://twitter.com/AthenusU/status/1372606271942230024

2021-03-18 17:55 UTC, spacepilotAV commented
Also let's look at the next line!
![image](https://user-images.githubusercontent.com/64748227/111673743-a92b7e00-87f1-11eb-82e3-23b9c3f6129b.png)

2021-03-18 18:17 UTC, marijuanARM commented
so what if you have code execution? i can make a hello world app & install it to my device and say i have code execution, because it is. unless it’s actual unsigned arbitrary code execution, it’s useless for actual jailbreaking, and you’re just using built in iOS features with no hacks involved whatsoever.

2021-03-18 18:26 UTC, spacepilotAV commented
code execution, on boot, without interaction. not useful whatsoever?

2021-03-18 18:29 UTC, spacepilotAV commented
and if you watched Geo's vid you would know there is actually some hacks involved in bypassing some parts of iOS, can't get into too much detail right now, but there is actual bypassing going on

we're not just a bunch of autists going "oOoHhH wOw lOk aTt UsS WeC anR uNcO deEE oN oUrrR pHoNESsss wWOWowoWOWOwow" there is actual shit going on

ok a lot of us are fucking autistic subliterate fucks but that doesn't change the fact that things are going on.

2021-03-18 18:58 UTC, 0x14307 commented
not to burst your bubble mate, but cussing everywhere like a crackhead with an AR-15 doesn't make you cooler

2021-03-18 19:02 UTC, spacepilotAV commented
A: that is a wonderful simile, thank you
B: didn't say it did
C: i'm getting very frustrated because i've been working on Athenus for quite literally years now, so I've been a bit frustrated with the people saying it's fake, though i understand why.

2021-03-18 19:27 UTC, Ecstxsy commented
glhf